# -*- coding: utf-8 -*-
"""model_answer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QWxudDlKy5hv_q6jJv7awraZQJxSFHai
"""

def add_numbers(a, b):
    result = a + b
    return result

def multiply_numbers(x, y):
    product = x * y
    return product